#!/bin/bash
# /home/me/app/bin/bcomp
if [ -f /home/me/app/bin/common.sh ]; then
    . /home/me/app/bin/common.sh
fi

# run win-bcomp-diff "$@"

meld "$@"

# msgbox "$@"
# args:
#   1 /tmp/rabbitvcs-46fcc80cea/rabbitvcs-1-HEAD-nofile.txt
#   2 /drive_d/game/tttt/nofile.txt